# coding: utf-8

# flake8: noqa

"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Book",
    "BookInput",
    "BookResponse",
    "BooksResponse",
    "Meta",
    "Review",
    "ReviewInput",
    "ReviewResponse",
    "ReviewsResponse",
    "User",
    "UserInput",
    "UserResponse",
    "UsersResponse",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.book import Book as Book
from openapi_client.models.book_input import BookInput as BookInput
from openapi_client.models.book_response import BookResponse as BookResponse
from openapi_client.models.books_response import BooksResponse as BooksResponse
from openapi_client.models.meta import Meta as Meta
from openapi_client.models.review import Review as Review
from openapi_client.models.review_input import ReviewInput as ReviewInput
from openapi_client.models.review_response import ReviewResponse as ReviewResponse
from openapi_client.models.reviews_response import ReviewsResponse as ReviewsResponse
from openapi_client.models.user import User as User
from openapi_client.models.user_input import UserInput as UserInput
from openapi_client.models.user_response import UserResponse as UserResponse
from openapi_client.models.users_response import UsersResponse as UsersResponse

