# coding: utf-8

"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_response import BookResponse

class TestBookResponse(unittest.TestCase):
    """BookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookResponse:
        """Test BookResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookResponse`
        """
        model = BookResponse()
        if include_optional:
            return BookResponse(
                data = openapi_client.models.book.Book(
                    id = 56, 
                    title = '', 
                    author = '', ),
                meta = openapi_client.models.meta.Meta(
                    timestamp = '2026-01-01T12:00:00', )
            )
        else:
            return BookResponse(
        )
        """

    def testBookResponse(self):
        """Test BookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
