# coding: utf-8

"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_book_reviews_get(self) -> None:
        """Test case for api_v1_book_reviews_get

        Get list of reviews
        """
        pass

    def test_api_v1_book_reviews_post(self) -> None:
        """Test case for api_v1_book_reviews_post

        Create review
        """
        pass

    def test_api_v1_book_reviews_review_id_delete(self) -> None:
        """Test case for api_v1_book_reviews_review_id_delete

        Delete review
        """
        pass

    def test_api_v1_book_reviews_review_id_get(self) -> None:
        """Test case for api_v1_book_reviews_review_id_get

        Get review by ID
        """
        pass

    def test_api_v1_books_book_id_delete(self) -> None:
        """Test case for api_v1_books_book_id_delete

        Delete book
        """
        pass

    def test_api_v1_books_book_id_get(self) -> None:
        """Test case for api_v1_books_book_id_get

        Get book by ID
        """
        pass

    def test_api_v1_books_get(self) -> None:
        """Test case for api_v1_books_get

        Get list of books
        """
        pass

    def test_api_v1_books_post(self) -> None:
        """Test case for api_v1_books_post

        Create new book
        """
        pass

    def test_api_v1_users_get(self) -> None:
        """Test case for api_v1_users_get

        Get list of users
        """
        pass

    def test_api_v1_users_post(self) -> None:
        """Test case for api_v1_users_post

        Create new user
        """
        pass

    def test_api_v1_users_user_id_delete(self) -> None:
        """Test case for api_v1_users_user_id_delete

        Delete user
        """
        pass

    def test_api_v1_users_user_id_get(self) -> None:
        """Test case for api_v1_users_user_id_get

        Get user by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
