# coding: utf-8

"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.review_response import ReviewResponse

class TestReviewResponse(unittest.TestCase):
    """ReviewResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReviewResponse:
        """Test ReviewResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReviewResponse`
        """
        model = ReviewResponse()
        if include_optional:
            return ReviewResponse(
                data = openapi_client.models.review.Review(
                    id = 56, 
                    rating = 56, 
                    comment = '', 
                    book_id = 56, 
                    user_id = 56, ),
                meta = openapi_client.models.meta.Meta(
                    timestamp = '2026-01-01T12:00:00', )
            )
        else:
            return ReviewResponse(
        )
        """

    def testReviewResponse(self):
        """Test ReviewResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
