# coding: utf-8

"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.book_input import BookInput

class TestBookInput(unittest.TestCase):
    """BookInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BookInput:
        """Test BookInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BookInput`
        """
        model = BookInput()
        if include_optional:
            return BookInput(
                title = '',
                author = ''
            )
        else:
            return BookInput(
                title = '',
                author = '',
        )
        """

    def testBookInput(self):
        """Test BookInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
