# coding: utf-8

# flake8: noqa
"""
    Book Management API

    API for managing books, users, and reviews

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.book import Book
from openapi_client.models.book_input import BookInput
from openapi_client.models.book_response import BookResponse
from openapi_client.models.books_response import BooksResponse
from openapi_client.models.meta import Meta
from openapi_client.models.review import Review
from openapi_client.models.review_input import ReviewInput
from openapi_client.models.review_response import ReviewResponse
from openapi_client.models.reviews_response import ReviewsResponse
from openapi_client.models.user import User
from openapi_client.models.user_input import UserInput
from openapi_client.models.user_response import UserResponse
from openapi_client.models.users_response import UsersResponse

